### PR TITLE
fix: include order for cpplint

### PR DESCRIPTION
**Pull request by wep21**
fix include order to pass cpplint linter test

### CODE REVIEW

**Comment by wxmerkt** [comment]
Thanks for the PR - I am aware of an issue with octomap on Jammy but haven't had the time to fix it yet. I could get back to this in ~1.5 weeks

**Comment by wep21** [comment]
@clalancette @nuclearsandwich could you also review this? This PR fixes regression test failure on rolling.
@wxmerkt I found out that build with `liboctomap-dev` was successful, while build with `ros-rolling-octomap` was failed.
I guess the header path was different. By the way, why do you release the ros2 package of `octomap` instead of registering rosdep key of `liboctomap-dev`?

**Comment by clalancette** [comment]
> @clalancette @nuclearsandwich could you also review this?

This looks generally fine to me, and is inline with what we had to do elsewhere when we updated the version of cpplint in use.

**Review by nuclearsandwich — COMMENTED** [review]
Personally I'd usually request / recommend that the PR description be edited to describe the cpplint warnings that the change is resolving but as this isn't my project to review I'll abstain from "binding" requests.

As far as the changes themselves I don't feel qualified to evaluate them without more information.

**Comment by clalancette** [comment]
> By the way, why do you release the ros2 package of `octomap` instead of registering rosdep key of `liboctomap-dev`?

I missed this last time.  It's a great question; someone in the past must have wanted it when it wasn't available, or too old a version.  That said, we really should be relying on the rosdep key if at all possible.  I'd be for that change, though we'd have to check what depends on `octomap` and if they'd be happy to use the rosdep key instead.

**Comment by wxmerkt** [comment]
Hi @wep21 and all,
In the past we had to release octomap into different distros as the liboctomap-dev versions differed across some of the supported operating system combinations (per REP-3 or REP-2000). I don't think this is the case anymore.

**From a quick check of available packages, I am in favour of removing ros-rolling-octomap and adding a rosdep key to the respective distribution versions.**

**Comment by wxmerkt** [comment]
I looked into the underlying failure more closely and it's due to a common issue with finding OctoMap, as it only sets CMake variables with upper-case OCTOMAP by default:

```find_package(octomap REQUIRED)``` will *NOT* set up the CMake variables correctly
```find_package(OCTOMAP REQUIRED)``` will.

As thus, the ament-auto-find-and-configure in the modified ROS2 CMakeLists fails. The reason non-rolling releases are fine is that I added patches to those releases to change the libdir from `lib/$arch` to `lib` and it incidentally gets configured correctly. Similarly, the reason it works with `liboctomap-dev` is that the paths incidentally are correct - not that the CMake configures correctly.

My current plan of action - independent from changing the rosdep key - is to modify Octomap's config.cmake to also set the `octomap_INCLUDE_DIRS` etc. variables with lower-case `octomap`.

**Comment by nuclearsandwich** [comment]
> My current plan of action - independent from changing the rosdep key - is to modify Octomap's config.cmake to also set the `octomap_INCLUDE_DIRS` etc. variables with lower-case `octomap`.

This would be great @wxmerkt. Please @ me directly if you'd like reviews.

**Comment by wxmerkt** [comment]
This has now been merged upstream (https://github.com/OctoMap/octomap/pull/369), but not yet released (and not sure if/when the [Ubuntu/RHEL/etc.] distro maintainers would make a new release either?).

As a current solution, we can add `target_include_directories(... PUBLIC ${OCTOMAP_INCLUDE_DIRECTORIES})` to the ROS2 branch in `octomap_ros` and `octomap_mapping` as well.

**Comment by wep21** [comment]
@wxmerkt I added workaround at https://github.com/OctoMap/octomap_ros/pull/15/commits/cfe4783575a90541299c76c42fa8e0a64f67c0bd.

**Comment by wxmerkt** [comment]
Thank you very much for the swift fix @wep21, and for the review and feedback @nuclearsandwich @clalancette

**Comment by wxmerkt** [comment]
New releases are out:
- Foxy: https://github.com/ros/rosdistro/pull/33184
- Galactic: https://github.com/ros/rosdistro/pull/33188
- Rolling: https://github.com/ros/rosdistro/pull/33189
- Humble: https://github.com/ros/rosdistro/pull/33190

**Pull request merged**
