### PR TITLE
drop PCL support

### PR DESCRIPTION
**Pull request by vrabaud**

### CODE REVIEW

**Comment by ahornung** [comment]
Great, thanks plenty! I'll update the release asap.

**Comment by vrabaud** [comment]
and one more on https://github.com/ros/common_msgs/pull/16
Can't wait for octomap_mapping :)

**Comment by ahornung** [comment]
octomap_server requires some more stuff from PCL. At least transforming 
point clouds, ground plane filtering, and a voxel grid filter are used 
internally.

**Comment by vrabaud** [comment]
are you interested in having it removed from the public API though ? insertScan is only interating over a pointcloud. Only filterGroundPlane is guilty then.

**Comment by ahornung** [comment]
Sure, that would be a start at least.

**Pull request merged**
