### PR TITLE
ROS2 Migration

### PR DESCRIPTION
**Pull request by wep21**

### CODE REVIEW

**Comment by wep21** [comment]
@wxmerkt I created a PR for ros2 migration. Could you create a branch named `ros2`? And then, I will change the target branch.

**Comment by wxmerkt** [comment]
Dear @wep21 
Thank you very much for the contribution. I've created the new branch and changed the target. Is this branch ready for merging then?

Best wishes,
Wolfgang

**Comment by wep21** [comment]
@wxmerkt Thanks for creating the branch. Yes, this is ready for merging. Also, I appreciate it if you could create a release PR toward `rosdistro` via `bloom`.

**Comment by wep21** [comment]
@wxmerkt Could you re-run github action before merging this just in case though I have already checked it on my fork repository?
https://github.com/wep21/octomap_ros/runs/4498633705?check_suite_focus=true

**Comment by wxmerkt** [comment]
Great, thank you for confirming. The GitHub Actions will only run once they are merged.

@cottsay - could you please create a `octomap_ros` release repository in ros2-gbp?

**Comment by wep21** [comment]
@wxmerkt Thank you for creating a release repositroy. https://github.com/ros/rosdistro/pull/31473
Could you also create a PR for `galactic` and `rolling`?

**Comment by wxmerkt** [comment]
I'm planning to create PRs for galactic and rolling once the one for foxy is merged and has successfully built

**Pull request merged**
